FROM jenkins/jenkins:lts
USER root

RUN apt-get update  \
    && apt-get install -y --no-install-recommends python3 python3-pip python3-venv  \
    && apt-get clean  \
    && rm -rf /var/lib/apt/lists/*


RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

RUN pip3 install uv


RUN jenkins-plugin-cli --plugins  \
    git workflow-aggregator allure-jenkins-plugin  \
    junit docker-workflow warnings-ng

USER jenkins
