[project]
name = "qa-pytest"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "requests>=2.33.1",
    "webob>=1.8.9",
]

[dependency-groups]
dev = [
    "isort>=6.0.1",
    "mypy>=1.20.0",
    "pre-commit>=4.5.1",
    "pytest==8.2.2",
    "ruff>=0.15.9",
]

# Linters

[tool.ruff]
extend = "ruff.toml"

[tool.ruff.lint]
unfixable = []


[tool.mypy]
python_version = "3.12"

follow_imports = "silent"
disable_error_code = "import-untyped"
ignore_missing_imports = true


[tool.pytest]
minversion = "8.2.2"

[tool.pytest.ini_options]
addopts = ["--strict-markers", "-s", "-v", "-p", "no:warnings"]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "smoke: basic smoke tests to verify critical functionality",
    "positive: tests only with correct result",
]
